carburants_analytics:
  outputs:
    dev:
      dbname: "{{ env_var('DB_DATABASE') }}"
      host: datawarehouse
      pass: "{{ env_var('DB_PASSWORD') }}"
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: "{{ env_var('DB_USER') }}"
    dev2:
      dbname: "{{ env_var('DB_DATABASE') }}"
      host: localhost
      pass: "{{ env_var('DB_PASSWORD') }}"
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: "{{ env_var('DB_USER') }}"
  target: dev # target par défaut
